### ISSUE TITLE
No support for macOS 11

### ISSUE THREAD

**Issue by emmaB93** [canonical/multipass#1664]
**Describe the bug**
After updating to OSX 11 Beta I'm not longer able to launch a new instance with multipass. The error message "Instance stopped while starting" appears always.

**To Reproduce**
How, and what happened?
1. Updating to macOS 11 Beta
2. `multipass launch`

**Expected behavior**
Instance will start as usual

**Logs**
Instance stopped while starting

**Additional info**
 - OS: macOS 11 Beta
-  multipass  1.3.0+mac
`Name:           active-filefish
State:          Stopped
IPv4:           --
Release:        --
Image hash:     438ddba6294b (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --`

**Additional context**
I uninstalled Multipass and a new installation did not worked.

**Comment by Saviq** [comment]
Hi @emmaB93, we've not yet gotten on the macOS 11 bandwagon, but could you (or anyone else affected!) please provide the daemon logs as per [our accessing logs docs](https://multipass.run/docs/accessing-logs)?

**Comment by Morialkar** [comment]
Hi, I have the same problem, as mentioned, here are my logs as required
[multipassd.log](https://github.com/canonical/multipass/files/4995151/multipassd.log)

**Comment by xiruizhao** [comment]
The current package installer failed on macOS 11 because `multipass-1.4.0+mac-Darwin-multipassd.pkg/Scripts/preinstall` uses `$( sw_vers -productVersion | cut -d. -f2 ) -lt 12 ` to detect incompatible macOS versions. 
Change it to `$( sw_vers -productVersion | cut -d. -f1 ) -eq 10 -a $( sw_vers -productVersion | cut -d. -f2 ) -lt 12` should fix this.

**Comment by byronrode** [comment]
> The current package installer failed on macOS 11 because `multipass-1.4.0+mac-Darwin-multipassd.pkg/Scripts/preinstall` uses `$( sw_vers -productVersion | cut -d. -f2 ) -lt 12 ` to detect incompatible macOS versions.
> Changing it to `$( sw_vers -productVersion | cut -d. -f1 ) -eq 10 -a $( sw_vers -productVersion | cut -d. -f2 ) -lt 12` can fix this problem.

Can confirm this works.

```
1. $ pkgutil --expand /path/to/installer.pkg /path/to/expanded
2. $ cd /path/to/expanded
3. $ cd multipass-1.4.0+mac-Darwin-multipassd.pkg/Scripts
4. $ vi preinstall 

...
edit version check conditional using the change from @xiruizhao above
...

5. pkgutil --flatten /path/to/expanded newpackagename.pkg
6. Run the GUI installer

**Comment by byronrode** [comment]
```
$ multipass version                                                                                                                                                                                                 
multipass  1.4.0+mac
multipassd 1.4.0+mac
```

Still cannot mount, but at least can confirm that can install 1.4.0 on Big Sur

**Comment by byronrode** [comment]
The daemon logs show the following (I tried to run `primary`)

```
[2020-08-20T12:13:40.810] [debug] [primary] process working dir ''
[2020-08-20T12:13:40.810] [info] [primary] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2020-08-20T12:13:40.810] [info] [primary] process arguments '-c, 1, -m, 1024M, -u, -A, -H, -U, 386bba5a-5dc4-3ac2-95c9-cf0b9a29b352, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/primary/pty,log=/Library/Logs/Multipass/primary-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2020-08-20T12:13:40.810] [info] [primary] process state changed to Starting
[2020-08-20T12:13:40.812] [info] [primary] process state changed to Running
[2020-08-20T12:13:40.821] [error] [primary] vmx_set_ctlreg: cap_field: 2 bit: 20 unspecified don't care
[2020-08-20T12:13:40.821] [error] [primary] Unable to create VM (22)
[2020-08-20T12:13:40.821] [info] [primary] vmx_init: processor does not support desired secondary processor-based controls

[2020-08-20T12:13:40.821] [info] [primary] process state changed to NotRunning
[2020-08-20T12:13:40.821] [info] [primary] process finished with exit code 1
```

**Comment by Saviq** [comment]
You should be able to get away [with VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-macos), the hyperkit backend doesn't yet work on 11.

**Comment by byronrode** [comment]
> You should be able to get away [with VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-macos), the hyperkit backend doesn't yet work on 11.

Virtualbox 6.1.1.12 won't install on Big Sur either. Seems the kext issue has reared it's head again.

**Comment by Saviq** [comment]
> I don't know that I'd put the blame on Hyperkit here as Docker has been working on every beta of MacOS 11 Big Sur.

Good to know, the log above suggested that might be the problem. We'll have to dig how we can fix, then.

**Comment by lukeholder** [comment]
This is still an issue on the latest MacOS beta. Does anyone working on this need more logs reproducing this show-stopper? @Saviq 

Hoping this is resolved before GM release of MacOS.

**Comment by planetf1** [comment]
I see the same behaviour on yesterday's new beta (20A5364e) - the workaround above does allow multipass to install,
but the instance never seems to get started with the log showing the entries as above

**Comment by lukeholder** [comment]
@planetf1 correct, the instances do not start

**Comment by jvacek** [comment]
I've been trying to get some Virtualisation happen on Big Sur DB6 and so far the only thing I was able to get running properly is the VMWare Fusion Tech Preview which mentions the code being rewritten to the new virtualisation API. Parallels 16 was very bugged, VBox did not happen at all. Here is the relevant article. https://blogs.vmware.com/teamfusion/2020/07/fusion-big-sur-tech-preview.html

**Comment by townsend2010** [comment]
Hey all, I have a [test package](https://multipass-ci.s3.amazonaws.com/pr1739/multipass-1.5.0-dev.236.pr1739%2Bga7214707.mac-Darwin.pkg) that fixes Multipass installing and running the Hyperkit backend on Big Sur.  Please give it a try and let us know how it goes.  Note that VirtualBox support is dependent on Oracle :smile:

**Comment by townsend2010** [comment]
Also, I'm not so sure about Docker for Mac running on Big Sur.  There are a slew of bugs being reported every day: https://github.com/docker/for-mac/issues?q=is%3Aissue+is%3Aclosed with the reply basically saying they don't support Big Sur yet.

**Comment by Morialkar** [comment]
I've been running Docker for Mac without issues since Beta 1 daily, not saying there is no issues, but those are some edge case, not base functionality issues. 

This is not the same trouble Multipass is having, as with Multipass I'm completely unable to run the actually software and access the VM. 

Apple has also done some PRs to Docker for Mac to help support Big Sur, which could explain the discrepancy between the functionality of Docker vs Virtual Box

**Comment by jvacek** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1302278/93389993-4589bd80-f86d-11ea-9d62-7e95b7b2b5c5.png">
@townsend2010 Thanks for the package, looking good! Will report back if I find anything.
P.s. the vbox reference was just for reference to clarify that the reason multipass wouldn't work was because the hyperkit usage needed to be adjusted, like vmware did.

**Comment by townsend2010** [comment]
@Morialkar, 

I don't know enough about Docker on Mac to be sure.  I was just going by all of the bug reports against Docker for Mac and not working on Big Sur :man_shrugging: 

Anyways, did you try the test Multipass package I posted above?  It *should* fix things for you.  If not, please report.

**Comment by planetf1** [comment]
@townsend2010 Just tried the test package which installed perfectly and allowed existing instances to launch, and new instance to be created.

However I seem to have no DNS resolution.  IP itself is fine so it may be specific to my setup (given combo of VPN, forced use of cisco umbrella for DNS redirection, using docker/k8s etc ...).

Obv I can update the nameserver, which seems to be 127.0.0.53 by default

**Comment by jvacek** [comment]
> However I initially had no DNS resolution. IP itself is fine so it may be specific to my setup (given combo of VPN, forced use of cisco umbrella for DNS redirection, using docker/k8s etc ...).

Haven't had issues with this out of the box. `apt`, `dig`, `traceroute` all work the way I'd have expected them to.

**Comment by townsend2010** [comment]
Hi @planetf1,

Glad it has (mostly) worked for you.  Yeah, I imagine the DNS resolution is something with your network setup.  We rely on vmnet/bootp and that is provided by macOS and that seems to be negatively impacted by VPN and other IP rules.

**Comment by byronrode** [comment]
Testing the package @townsend2010 and will feedback if I notice anything. I am going to drop-in replace my current implementation and see if all my machines run etc.

**Comment by byronrode** [comment]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/382018/93474454-a4941480-f8f7-11ea-88a3-20bbb6c9e0ec.png">

So far so good.

**Comment by planetf1** [comment]
Thanks. As an aside for my issue I read to read through https://askubuntu.com/questions/1012641/dns-set-to-systemds-127-0-0-53-how-to-change-permanently - but multipass looking good. Thanks!

**Comment by byronrode** [comment]
@townsend2010 I tested everything on the `craftcms/nitro` machines, from top to bottom, tested functionality, networking etc, and all seems great and working without issues, so this passes my testing. Can also confirm that `hyperkit` seems to be running within valid ranges. Nitro uses 4GB on the machine and it was running just over 4GB of memory.

Tests passed 🥇 

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/382018/93483265-ef665a00-f900-11ea-8f5a-5f7f0d0c9629.png">

**Comment by Saviq** [comment]
Hi all, our upcoming 1.5 release will have the fix in. Stay tuned.

**Comment by mindfactory-se** [comment]
My logs
---
[2020-11-14T16:02:19.310] [debug] [primary] process working dir ''
[2020-11-14T16:02:19.310] [info] [primary] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2020-11-14T16:02:19.310] [info] [primary] process arguments '-c, 1, -m, 1024M, -u, -A, -H, -U, 386bba5a-5dc4-3ac2-95c9-cf0b9a29b352, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/primary/pty,log=/Library/Logs/Multipass/primary-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2020-11-14T16:02:19.310] [info] [primary] process state changed to Starting
[2020-11-14T16:02:19.312] [debug] [primary] Trying SSH on 192.168.64.3:22
[2020-11-14T16:02:19.313] [info] [primary] process state changed to Running
[2020-11-14T16:02:19.330] [error] [primary] vmx_set_ctlreg: cap_field: 2 bit: 20 unspecified don't care
[2020-11-14T16:02:19.330] [error] [primary] Unable to create VM (22)
[2020-11-14T16:02:19.330] [info] [primary] vmx_init: processor does not support desired secondary processor-based controls

**Comment by jose-neta** [comment]
0. using Multipass 1.4
1. Update to Mac OS X 11 (Multipass is broken)
2. brew upgrade Multipass (all good now with Multipass 1.5)

thank you so much of Multipass

**Comment by Saviq** [comment]
@mindfactory-se, what's your hardware? Your CPU does not have the required functionality:

```
[2020-11-14T16:02:19.330] [info] [primary] vmx_init: processor does not support desired secondary processor-based controls
```

**Comment by townsend2010** [comment]
@mindfactory-se,

It appears you may not be running the latest version of Multipass.
```
[error] [primary] vmx_set_ctlreg: cap_field: 2 bit: 20 unspecified don't care
```

This should have been fixed in version 1.5. What version are you running?
