### ISSUE TITLE
Cloud-init permissions field type incorrectly parsed as integer (e.g., 0755 → 493)

### ISSUE THREAD

**Issue by srbouffard** [canonical/multipass#4176]
**Description**

When launching a Multipass instance with a valid cloud-init YAML config that includes a `write_files` section with:

```yaml
permissions: "0755"
```

Multipass appears to convert this value into an **integer** (`493`) when it hands off the config to the VM, resulting in a cloud-init schema validation warning or failure:

```
Cloud config schema errors: write_files.0.permissions: 493 is not of type 'string'
```

Even though the original YAML correctly specifies `"0755"` (as a string), the cloud instance receives:

```yaml
permissions: 493
```

This results in the launch command failing for a timeout.

---

**Steps to Reproduce**

1. Launch a multipass instance using the charm-dev cloud-init:
```bash
multipass launch --name cdo --cpus 4 --memory 8G --disk 50G --cloud-init https://raw.githubusercontent.com/canonical/multipass/refs/heads/main/data/cloud-init-yaml/cloud-init-charm-dev.yaml
```

2. Wait until command terminates or times out
```bash
launch failed: The following errors occurred:
timed out waiting for initialization to complete
```

3. Enter the instance and inspect the cloud init schemas:
```bash
multipass shell cdo
sudo cloud-init schema --system
  Found cloud-config data types: user-data, vendor-data, network-config

  1. user-data at /var/lib/cloud/instances/cdo/cloud-config.txt:
    Invalid user-data /var/lib/cloud/instances/cdo/cloud-config.txt
    Error: Cloud config schema errors: write_files.0.permissions: 493 is not of type 'string'
  ...
```
> Cloud-init logs also show a schema validation warning related to this field.

5. Inspecting the cloud config reveals the file does in fact contain an integer rather than the originally specificed string:
```bash
sudo cat /var/lib/cloud/instances/cdo/cloud-config.txt | grep permission
    permissions: 493
```

**Expected Behavior**

Multipass should preserve string types in YAML, especially for fields like `permissions`, which cloud-init strictly expects to be strings (e.g., `"0644"`, `"0755"`). There should be no implicit conversion to integers.

---

**Workaround**

Manually force the value to be treated as a string using YAML type tags:

```yaml
permissions: !!str "0755"
```

But this workaround shouldn't be necessary for already well-formed YAML.

---

**Environment**

* Multipass version: 1.15.1
* Host OS: 24.04 (Canonical corporate laptop)
* Guest OS: Ubuntu 24.04 (default)
* Cloud-init version in guest: (optional)

---

**Suggested Fix**

Ensure the YAML parser used in Multipass preserves string types for cloud-init passthrough and does not interpret values like `"0755"` into integers.

---

**Comment by levkropp** [comment]
Hi @srbouffard , thank you for reporting this issue! I've been able to reproduce this and have already implemented a fix for this issue in a PR to [improve handling of YAML emission in Multipass](https://github.com/canonical/multipass/pull/4177). 

This seems to be related to how `yaml-cpp` handles re-emission of scalars, because as you have pointed out `cloud-init-charm-dev.yaml` is indeed correct YAML. 

Once the fix is merged, launching an instance with the charm-dev cloud-init will work correctly.  Thanks again for the thorough report!

**Comment by srbouffard** [comment]
Hi @levkropp great news!

Thanks for the quick response and fix :)

**Comment by Niketin** [comment]
I see this has been merged and it should be part of the 1.16.1, correct? I am still seeing this error on version `1.16.1+win`.

I followed @srbouffard's [instructions](https://github.com/canonical/multipass/issues/4176#issue-3164120022) and the error happens exactly as he describes.

Could this issue be reopened?

**Comment by Niketin** [comment]
> I see this has been merged and it should be part of the 1.16.1, correct? I am still seeing this error on version `1.16.1+win`.
> 
> I followed [@srbouffard](https://github.com/srbouffard)'s [instructions](https://github.com/canonical/multipass/issues/4176#issue-3164120022) and the error happens exactly as he describes.
> 
> Could this issue be reopened?

My bad, this fix hasn't been in any release yet.

**Comment by jamroks** [comment]
Hi all, 

I have just been bit by that same bug .I'm running on : multipass   1.16.1+Mac . do we know if this is going to make it in the next release and when would that be approximatly ?

**Comment by ricab** [comment]
Hey @jamroks, this is fixed but not yet released.

**Comment by jamroks** [comment]
> Hey @jamroks, this is fixed but not yet released.

That's great news @ricab thanks. Do you happen to know by any chance when will the next release be available ?

**Comment by ricab** [comment]
@jamroks I don't have a date, but we're aiming for a patch release in a few weeks. You can also try one of our development builds if you want:

- `snap install/refresh --edge multipass` (auto updates)
- https://multipass-ci.s3.amazonaws.com/ci3389/multipass-1.17.0-dev.ci3389%2Bge724df05.win-win64.msi
- https://multipass-ci.s3.amazonaws.com/ci3389/multipass-1.17.0-dev.ci3389%2Bge724df05.mac-Darwin.pkg

**Comment by jamroks** [comment]
Thanks, I'll wait the stable patch release since I'm macOS Tahoe
