### ISSUE TITLE
Configure DNS with a local `.multipass` domain

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#666]
To be able to `ping <instance>` from inside another instance, we need to set up a search domain through the DHCP server. Otherwise `systemd-resolved` refuses to resolve the name.

On QEMU, it should be as easy as adding `--domain multipass,local` to the `dnsmasq` command line.

On Hyper-V, `.mshome.net` is added by default, we should ensure it's in the search domains via `cloud-init`.

On macOS `bootp` isn't set up to give out a search domain, so we'd need to configure `systemd-resolved` to allow no-suffix lookups.

**Comment by townsend2010** [comment]
This is fixed, so closing.

**Comment by sciabarracom** [comment]
Just tried with 0.7.0 , I have 2 vms, kube-master and kube-node1

multipass@kube-master:~$ ping kube-node1
ping: kube-node1: Temporary failure in name resolution
multipass@kube-master:~$ ping kube-node1.multipass
ping: kube-node1.multipass: Name or service not known

**Comment by Saviq** [comment]
@sciabarracom can you please provide `systemd-resolve --status` from the two instances?

**Comment by sciabarracom** [comment]
$ systemd-resolve --status
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 22 (vethwepla3dc978)
      Current Scopes: none

$ systemd-resolve kube-node1.multipass kube-master.multipass
kube-node1.multipass: resolve call failed: 'kube-node1.multipass' not found
kube-master.multipass: resolve call failed: 'kube-master.multipass' not found

**Comment by sciabarracom** [comment]
The bug still happens with 0.7.1 I am using a Mac
Different error messages

multipass@kube-node1:~$ ping kube-master
ping: kube-master: Temporary failure in name resolution
multipass@kube-master$ ping kube-node1.multipass
ping: kube-node1.multipass: Name or service not known

**Comment by Saviq** [comment]
Hi @sciabarracom see the last point in the issue description, on macOS `bootp` is used and it doesn't give out any search domains (as can be seen in the `--status` output).

Despite the description, this issue was about Linux and the qemu backend. I've now split #853 out to track the macOS problem.
